name: Willow Home Properties
favicon: null
layout_spectrum: 0.31853
typography_spectrum: 0.03992750542238355
title: Willow Home Properties
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#005392'
    - '#0a0a0a'
    - '#383838'
    - '#898989'
    - '#ecfcff'
  brandStrength: 0.75
  lightness: 0.9375
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
