name: Willow Home Properties
favicon: null
layout_spectrum: 0.5308033623732626
typography_spectrum: 0.4021851506549865
title: Willow Home Properties
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#005392'
    - '#0A0A0A'
    - '#EDFDFF'
    - '#383838'
    - '#97B7CD'
  brandStrength: 0.3775765581522137
  lightness: 0.5801303472835571
  saturation: 0.7378181803505868
  rhythmicContrast: 0.8419481487944722
purpose: []
