name: Willow Home Properties
favicon: null
layout_spectrum: 0.8823130587115884
typography_spectrum: 0.03992750542238355
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6733383650425822
  lightness: 0.962145000230521
  saturation: 0.4666922087781131
  rhythmicContrast: 0.6608292304445058
purpose: []
